### ISSUE TITLE
Hyrax - Make number of cores tunable

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#18]
The number of cores on the RoR host machine should be tunable. 

This affects RAILS_MAX_THREADS and the db pool.

**Comment by orangewolf** [comment]
1) https://github.com/cu-library/hyrax-ansible/blob/master/roles/hyrax/templates/puma.service#L30 concurrency should probably be a variable to make tuning easier. It is very much function of the size of your box / number of cores you have.

2) same with the number of sidekiq workers (currently just uses the default) https://github.com/cu-library/hyrax-ansible/blob/master/roles/hyrax/templates/sidekiq.service
