### ISSUE TITLE
Hyrax - Database backed NOID state

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#28]
Docs at https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#database-backed-minter-state

**Comment by cudevmaxwell** [comment]
https://github.com/cu-library/hyrax-ansible/blob/master/roles/hyrax/templates/hyrax.rb#L77, so the only thing left to do is to add `rails generate active_fedora:noid:install` to the ansible scripts after installation.

**Comment by orangewolf** [comment]
This is no longer required - docs have not been updated (there's an open PR I believe). Your currently good to go on minter in database with the default Hyrax install.

**Comment by cudevmaxwell** [comment]
Good to see they changed the default behavior.
