### ISSUE TITLE
Nginx - Production optimizations in hyrax.conf

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#3]
Does the Nginx configuration for Hyrax, `hyrax.conf`, need any tweaks?

**Comment by cudevmaxwell** [comment]
For example, hyrax.conf should allow for TLS if cert is generated. 

We proxy behind haproxy which does our TLS termination, but we should encrypt the proxy to backend connection anyway.

**Comment by cudevmaxwell** [comment]
Another example: caching at the nginx level. Needed?

**Comment by orangewolf** [comment]
We don't need any more to have a well functioning production Nginx config. End to end TLS support is probably its own significant initiative. Lots of choices here (make LetsEncrypt an option? Manditory? How are certs uploaded? etc).

**Comment by cudevmaxwell** [comment]
I agree, more specific Nginx config is too dependent on other factors.
