### ISSUE TITLE
Ruby - Puma, sidekiq, and ruby-install feedback. 

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#33]
The following should be reviewed to ensure we're following the RoR community's best practices for production deployment:

- The ansible steps in `roles/hyrax/tasks/main.yml` ,
- Using puma as the production server.
- The `puma.service` and `sidekiq.service` unit files (better restart on error behavior? Different ENV?)
- `puma.rb` (Any production tweaks?)

**Comment by cudevmaxwell** [comment]
See issue #43, something is seriously wrong.

**Comment by orangewolf** [comment]
@cudevmaxwell couple things in `roles/hyrax/tasks/main.yml` I wanted to talk through:

1) It feels odd to me to be creating a Hyrax running Rails app on the live production server. Almost all Hyrax installs get customized and not run stock, which you can't really do with out having a repo where you edit the app and then later deploy it. A lot of this set up would hold, but a more common setup would be for the gem installs and app configuration to happen locally and then be deployed via Capistrano or Ansistrano (I like the later because it drops one whole tool, you already have Ansible). 

Is the goal here really to just install the stock component and configure it on the prod server? Is this a demo instance then? What happens when someone changes a view file, a translation or writes a custom model? 


2) There are 2 rake tasks that should be added irrespective of the answers to (1).  When you create a brand new database you need to create the default work types and the initial admin set:

`rails hyrax:default_collection_types:create hyrax:default_collection_types:create`. I can add those unless you left them out on purpose.

3) SMTP in production.rb probably needs more options: username/password/tls/domain are all pretty commonly required.  We should also set the default_host for email as Rails will not guess it.

4) https://github.com/cu-library/hyrax-ansible/blob/master/roles/hyrax/templates/puma.service#L30 concurrency should probably be a variable to make tuning easier. It is very much function of the size of your box / number of cores you have.

5) same with the number of sidekiq workers (currently just uses the default) https://github.com/cu-library/hyrax-ansible/blob/master/roles/hyrax/templates/sidekiq.service

6) I think logrotate needs the following options so that puma can continue to write its open file descriptor:
```
  delaycompress
  copytruncate
```

7) I really dig your backup scripts

8) nginx config looks good. 

9) I'm not seeing a puma.rb file, are you using the stock one currently? if so we need to commit a template that enables some of the options like concurrency and properly connects and disconnects things on forking.

**Comment by cudevmaxwell** [comment]
1:

We will definitely be making some small changes to the templates and likely the forms, maybe even the models at some point. 

This is one of the reasons I wanted to bring in someone with more Rails experience. I'm treating Hyrax more like a Python/Go dependency or Drupal module: You install it in production and the application code doesn't really touch it. For example, in Python, I don't have to change the source code of Flask to create a web service using Flask. I can also update to a new version of Flask without changing the application code. 

So, for dev -> test -> prod, I was thinking: 

We run these ansible roles on a dev server, `git init` at `/var/www/hyrax/hyrax-root/`, and push that to a new github repo. We exclude from the repo temp files, logs, and `vendor/bundle`, where the gems are installed.  

We run these ansible roles on the test and prod servers, `git init` at /var/www/hyrax/hyrax-root/, set the github repo as 'upstream', and pull down changes as we need to. 

To bump hyrax versions, we just up the version in common.yml, and rerun these ansible roles on dev, then test, then prod. 

If upping Hyrax versions changes files outside `vendor/bundle`, this obviously won't work, as changes we've made might be overwritten. 

Is it better to have our 'hyrax project', dependencies and all, in one github repo? https://github.com/ansistrano/deploy looks really promising if we wanted to go this route, I like being able to roll back quickly. I wonder how it handles db migrations.

**Comment by cudevmaxwell** [comment]
2. 

I looked into this in #17 , and I think they're safe to run over and over. A `changed_when` False would be appropriate, since I don't think we can check if they've been run before. 

`hyrax:default_collection_types:create` -> https://github.com/samvera/hyrax/blob/master/lib/tasks/default_collection_type.rake 

Looks safe. 

`hyrax:default_admin_set:create` -> https://github.com/samvera/hyrax/blob/master/lib/tasks/default_admin_set.rake

Looks safe. 

`hyrax:workflow:load` -> https://github.com/samvera/hyrax/blob/master/lib/tasks/workflow.rake

Not sure about this one...

Adding `hyrax:default_collection_types:create` and `hyrax:default_admin_set:create` would be great.

**Comment by cudevmaxwell** [comment]
3. 

"Var"ing up the SMTP config would be great, good catch.

**Comment by cudevmaxwell** [comment]
6. 

Sounds good, good catch.

**Comment by cudevmaxwell** [comment]
7.

Thank you, thank you 😄

**Comment by cudevmaxwell** [comment]
Happy to see these issues resolved with the latest pull request. Thanks again @orangewolf and the whole Notch8 crew.

**Comment by cudevmaxwell** [comment]
#52 was introduced by https://github.com/cu-library/hyrax-ansible/pull/50

**Comment by cudevmaxwell** [comment]
Task "Configure initial collection types and workflows" now fails on test CentOS Vagrant with this error:

```
rails aborted!
Ldp::NotFound: 
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:11 9:in `block in check_for_errors'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:117:in `tap'
/var/www/hyrax/shared/vendor/b undle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:117:in `check_for_errors'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/meth ods.rb:96:in `block in put'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/var/www /hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:88:in `put'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/ lib/active_fedora/caching_connection.rb:24:in `put'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connectio n.rb:61:in `rescue in init_base_path'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:53:in `in it_base_path'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:41:in `put'
/var/www/hyrax/share d/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/resource.rb:84:in `create'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_sourc e.rb:20:in `create'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:180:in `_create_record'
/var/www/hyrax /shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:64:in `_create_record'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/a ctive-fedora-11.5.2/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/activ e_support/callbacks.rb:131:in `run_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_cr eate_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:240:in `_create_record'
/var/www/hyrax/share d/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:172:in `create_or_update'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/a ctive-fedora-11.5.2/lib/active_fedora/callbacks.rb:236:in `block in create_or_update'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/act ive_support/callbacks.rb:131:in `run_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_ save_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:236:in `create_or_update'
/var/www/hyrax/sha red/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:33:in `save'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedor a-11.5.2/lib/active_fedora/validations.rb:50:in `save'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/services/hyrax/admin_set_create_service.rb :57:in `create'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/services/hyrax/admin_set_create_service.rb:21:in `create_default_admin_set'
/var /www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/models/admin_set.rb:59:in `find_or_create_default_admin_set_id'
/var/www/hyrax/shared/vendor/bundle/r uby/2.5.0/gems/hyrax-2.3.3/lib/tasks/default_admin_set.rake:5:in `block (3 levels) in <top (required)>'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties- 5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rak e_command.rb:18:in `perform'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/var/www/hyrax/shared/vendor/bun dle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Ldp::NotFound: 
/ var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:119:in `block in check_for_errors'
/var/www/hyrax/shared/vendor/bundle/ruby/2. 5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:117:in `tap'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:117:in `check_for_e rrors'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:25:in `block in head'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/ gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods .rb:17:in `head'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:56:in `init_base_path'
/var/w ww/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:41:in `put'
/var/www/hyrax/shared/vendor/bundle/ruby/ 2.5.0/gems/ldp-0.7.2/lib/ldp/resource.rb:84:in `create'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/resource/rdf_source.rb:20:in `create'
 /var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:180:in `_create_record'
/var/www/hyrax/shared/vendor/bundle /ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:64:in `_create_record'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/l ib/active_fedora/callbacks.rb:240:in `block in _create_record'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.r b:131:in `run_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/var /www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:240:in `_create_record'
/var/www/hyrax/shared/vendor/bundle/ruby/ 2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:172:in `create_or_update'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/l ib/active_fedora/callbacks.rb:236:in `block in create_or_update'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks .rb:131:in `run_callbacks'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/var /www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/callbacks.rb:236:in `create_or_update'
/var/www/hyrax/shared/vendor/bundle/rub y/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/persistence.rb:33:in `save'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_f edora/validations.rb:50:in `save'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/services/hyrax/admin_set_create_service.rb:57:in `create'
/var /www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/services/hyrax/admin_set_create_service.rb:21:in `create_default_admin_set'
/var/www/hyrax/shared/ven dor/bundle/ruby/2.5.0/gems/hyrax-2.3.3/app/models/admin_set.rb:59:in `find_or_create_default_admin_set_id'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/hyrax- 2.3.3/lib/tasks/default_admin_set.rake:5:in `block (3 levels) in <top (required)>'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/comma nds/rake/rake_command.rb:21:in `block in perform'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `p erform'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/var/www/hyrax/shared/vendor/bundle/ruby/2.5.0/gems/r ailties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => hyrax:default_admin_set:create
```

**Comment by orangewolf** [comment]
That means fedora is either not coming up or not happy. I’ll spin up that
image and take a look.


-- 
Rob Kaufman
