### ISSUE TITLE
All Components - Performance review

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#37]
These roles should install Hyrax and it's components so that a reasonably provisioned server can respond to most requests quickly while under moderate load. This is an intentionally loose goal, as no testing has been done to set a baseline. 

The performance testing should include things like viewing large RIIIF images, uploading large video files, streaming large video files, and searching among hundreds of thousands of objects. 

500 milliseconds is my personal unacceptable response time. The README document should include minimum recommended server specs to avoid slow response times.

**Comment by DraxIndustries79** [comment]
[Carleton Performance Review.pdf](https://github.com/cu-library/hyrax-ansible/files/3030607/Carleton.Performance.Review.pdf)
