### ISSUE TITLE
Tomcat - What version should be used?

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#4]
Does it matter if Tomcat[7/8] is used? Fedora 4 docs say to use Tomcat 7 https://wiki.duraspace.org/display/FEDORA475/Deploying+Fedora+4+Complete+Guide#DeployingFedora4CompleteGuide-DeployingwithTomcat7 but tomcat 8 is installed by the `fedora4` role.

**Comment by cudevmaxwell** [comment]
After one is selected, the https://github.com/cu-library/hyrax-ansible#software-versions section of the README should be updated.

**Comment by orangewolf** [comment]
It doesn't make any real difference to the running WAR and 8 seems easier to install as its in current package managers. It feels to me like it is documented well currently, is there more needed here?

**Comment by cudevmaxwell** [comment]
No, just wanted to ensure there wasn't a gotcha I wasn't aware of. Thanks @orangewolf
