### ISSUE TITLE
Hyrax - Task "Run rails generate hyrax:install" fails.

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#43]
`Specified 'sqlite3' for database adapter`

**Comment by cudevmaxwell** [comment]
Hopefully fixed in de8050708dfabb984

**Comment by cudevmaxwell** [comment]
`/var/www/hyrax/hyrax-root/vendor/bundle/ruby/2.5.0/gems/hyrax-2.4.1/app/search_builders/hyrax/collection_search_builder.rb:10:in `<module:Hyrax>': uninitialized constant SearchBuilder (NameError)`

**Comment by cudevmaxwell** [comment]
Trying hyrax 2.4.0

**Comment by cudevmaxwell** [comment]
Frustrating, I can't see why this would be failing now.

**Comment by cudevmaxwell** [comment]
Not just a Hyrax issue, even rails console fails. This is a new problem, with no significant changes to the scripts to account for it.

**Comment by cudevmaxwell** [comment]
Maybe the way Ruby/Gem are installed and the way a local bundle directory is used is completely wrong. But why did it work before?

**Comment by brianmcbride** [comment]
Try updating the Gemfile to `gem 'sqlite3', '~> 1.3.0'` and run bundle install. I believe the community is working on a fix for the issue.

**Comment by orangewolf** [comment]
^ this - it broke basically every rails app out there.  Better yet for this install it might be worth removing sqlite all together if you don't need it and only doing Postgres.

**Comment by orangewolf** [comment]
@cudevmaxwell let me know if you'd like a PR that just takes sqlite3 out of the equation.

**Comment by cudevmaxwell** [comment]
I've made a change here: https://github.com/cu-library/hyrax-ansible/commit/a092b482bff1f4515a2832e9d11ad4465eac79f9

I'll test that next week to see if that fixed it, thanks @orangewolf and @brianmcbride.

**Comment by cudevmaxwell** [comment]
Downgrading the sqlite3 gem to 1.3.0 did not fix the error.

```
<module:Hyrax>: uninitialized constant SearchBuilder (NameError)
```

**Comment by cudevmaxwell** [comment]
Fixed!
