### ISSUE TITLE
Hyrax - "Populate service facts" task in after_symlink.yml is empty. 

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#52]
cc @orangewolf

**Comment by cudevmaxwell** [comment]
This blocks #51

**Comment by orangewolf** [comment]
Are you getting an error? Which OS? 

https://docs.ansible.com/ansible/latest/modules/service_facts_module.html is where that line comes from - the goal is to keep puma or sidekiq from starting on the first deploy (as they don't exist as services yet and will restart once they do).

**Comment by cudevmaxwell** [comment]
49e5489a58870a057dcdece38e9d might have fixed this, I think it was just a yml parsing issue.

**Comment by cudevmaxwell** [comment]
Fixed.
